config/routes.rb
Rails.application.routes.draw do

  devise_for :legal_people, path: 'legal_people', controllers: { sessions: "legal_people/sessions", registrations: "legal_people/registrations"}
  shallow do
    resources :legal_people do
      resources :accounts do
        resources :transactions
      end
    end
  end

  devise_for :people, path: 'people', controllers: { sessions: "people/sessions", registrations: "people/registrations"}
  shallow do
    resources :people do
      resources :accounts do
        resources :transactions
      end
    end
  end

  root to: 'pages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
require './App/services/transaction_services/update_account_balance_service.rb'
require './App/services/transaction_services/transfer_service.rb'

class TransactionsController < ApplicationController
  include Devise::Controllers::Helpers
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_action :set_account, only: [:new, :index, :create, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = @account.transactions
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.amount *= 100 if @transaction.amount
    @transaction.receiver_id = @account.id

    if (@transaction.is_a?(Transfer))
      @transaction.sender_id = @account.id
      @transaction.receiver_id = transaction_params[:receiver_id]
    end

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transaction_path(@transaction), notice: 'Account transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
        #   TransactionServices::UpdateAccountBalanceService.new({
        #   transaction_params: {
        #     transaction: @transaction,
        #     account: @account
        #   }
        # }).execute

        # if (@transaction.is_a?(Transfer))
        #   @transaction.sender_id = @account.id
        #   @transaction.receiver_id = transaction_params[:receiver_id]
        #   if (@account.balance >= @transaction.amount )
        #     TransactionServices::TransferService.new({
        #     transaction_params: {
        #       transaction: @transaction,
        #       account: @account,
        #       current_user: @current_user
        #     }
        #   }).execute
        #   else
        #     flash[:error] = "transfer is not possible because transfer amount is more than account balance!"
        #   end
        # end
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_path(@transaction), notice: 'Account transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transactions = @account.transactions
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transaction_path(@transactions), notice: 'Account transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    def set_account
      @account = Account.find(params[:account_id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:amount, :type, :number, :receiver_id)
    end
end

app/views/transactions/_form.html.erb
<%= form_for([@account, transaction], as: :transaction, url: transaction.persisted? ? account_transaction_path(@account, transaction) : account_transactions_path(@account)) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :amount %>
    <%= form.text_field :amount, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :type %>
    <%= form.select :type, options_for_select([["Select one please", ""], ["Deposit", "Deposit"], ["Contribute", "Contribution"], ["Transfer", "Transfer"]]), class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :number %>
    <%= form.text_field :number, class: "form-control" %>
  </div>

  <div id="receiver-block" class="form-group hidden">
    <%= form.label :receiver_id %>
    <%= form.select :receiver_id, options_for_select(["Select one please", ""] + @account.other_accounts.collect{ |u| [u.name, u.id] }), class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Account Transaction</h1>

<%= render 'form', account_transaction: @account_transaction %>

<%= link_to 'Show', @account_transaction %> 

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Account Transactions</h2>

<table class= "table table-bordered">
  <thead>
    <tr>
      <th>Amount</th>
      <th>Transaction type</th>
      <th>Transaction number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= number_to_currency transaction.amount_in_dollars %></td>
        <td><%= transaction.type %></td>
        <td><%= transaction.number %></td>
        <td>
        <div class="dropdown">
            <a class="btn btn-secondary dropdown-toggle" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Action
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <li> <%= link_to 'View', transaction_path(transaction) %></li>
              <li> <%= link_to 'Edit', edit_transaction_path(transaction) %></li>
              <li><%= link_to 'Destroy', transaction_path(transaction), method: :delete, data: { confirm: 'Are you sure?' } %></li>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Make a New Account Transaction', new_account_transaction_path %>

app/views/transactions/new.html.erb
<h2>Please select the type of transaction:</h2>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', account_transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Transaction type:</strong>
  <%= @transaction.type %>
</p>

<p>
  <strong>Transaction number:</strong>
  <%= @transaction.number %>
</p>

<p>
  <strong>Account:</strong>
  <%= @transaction.receiver_id %>
</p>



<%= link_to 'Edit', edit_transaction_path(@transaction) %>