config/routes.rb
Rails.application.routes.draw do

  devise_for :legal_people, path: 'legal_people', controllers: { sessions: "legal_people/sessions", registrations: "legal_people/registrations"}
  shallow do
    resources :legal_people do
      resources :accounts do
        resources :transactions
      end
    end
  end

  devise_for :people, path: 'people', controllers: { sessions: "people/sessions", registrations: "people/registrations"}
  shallow do
    resources :people do
      resources :accounts do
        resources :transactions
      end
    end
  end

  root to: 'pages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<div class="container-fluid">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "Account control System", root_path, class:"navbar-brand" %> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      

      <form class="form-inline my-2 my-lg-0">
        <ul class="nav navbar-nav ml-auto">
        <% if person_signed_in? || legal_person_signed_in? %>
            

          <div class="dropdown">
            <a class="btn btn-info dropdown-toggle" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= (person_signed_in?) ? current_person.email : current_legal_person.email %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              
              <% if person_signed_in? %>
                <li> <%= link_to 'Manage accounts', person_accounts_path(current_person) %> </li>
                <li> <%= link_to "Edit Profile", edit_person_registration_path, class: "nav_link" %> </li>
                <li> <%= link_to "Sign Out", destroy_person_session_path, class: "nav_link", method: :delete %> </li>
              <% else %>
              <li> <%= link_to 'Manage accounts', legal_person_accounts_path(current_legal_person) %> </li>
              <li> <%= link_to "Edit Profile", edit_legal_person_registration_path, class: "nav_link" %> </li>
              <li> <%= link_to "Sign Out", destroy_legal_person_session_path, class: "nav_link", method: :delete %> </li>
              <% end %>
            </ul>    
          </div>  
        <% else %>
          <li class="nav-item">
            <%=link_to "Sign Up as real person", new_person_registration_path,  class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%=link_to "Sign Up as legal person", new_legal_person_registration_path,  class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%=link_to "Sign In as real person ", new_person_session_path,  class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%=link_to "Sign In as legal person ", new_legal_person_session_path,  class: "nav-link" %>
          </li>
        <% end %>        
        </ul>
      </form>
    </div>
  </nav>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AccountControl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container-fluid">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= content_tag :div, msg, :id=> "flash_#{name}" %>
        </div>
      <% end %>
    <% end %> 
    <%= yield %>
  </div>
  </body>
</html>