config/routes.rb
Rails.application.routes.draw do

  devise_for :legal_people, path: 'legal_people', controllers: { sessions: "legal_people/sessions", registrations: "legal_people/registrations"}
  shallow do
    resources :legal_people do
      resources :accounts do
        resources :transactions
      end
    end
  end

  devise_for :people, path: 'people', controllers: { sessions: "people/sessions", registrations: "people/registrations"}
  shallow do
    resources :people do
      resources :accounts do
        resources :transactions
      end
    end
  end

  root to: 'pages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
# class Account < ApplicationRecord
#   belongs_to :parent, class_name: "Account", optional: true
#   has_many :children, class_name: "Account", foreign_key: "parent_id"
#   belongs_to :accountable, polymorphic: true
#   has_many :account_transactions
#
#   validates :name, presence: true, uniqueness: true
#   validates :balance, presence: true, numericality: true
#   validates :status, presence: true
#
#
#   def parent_name
#     # it may not have a parent
#     parent.try(:name)
#   end
#
#   def has_parent?
#     parent.present?
#   end
#
#   def has_children?
#     children.exists?
#   end
#
# end

class Account < ApplicationRecord
  has_many :children, class_name: "BranchAccount", foreign_key: "parent_id"
  belongs_to :accountable, polymorphic: true
  has_many :account_transactions

  has_many :received_transactions, foreign_key: :receiver_id, class_name: "Transaction"
  has_many :sent_transactions, foreign_key: :sender_id, class_name: "Transaction"

  validates :name, presence: true, uniqueness: true
  validates :balance, presence: true, numericality: true
  validates :status, presence: true

  def parent_name
    nil
  end

  def has_parent?
    false
  end

  def has_children?
    children.exists?
  end

  def transactions
    received_transactions + sent_transactions
  end

  def balance
    received_transactions.sum(:amount) - sent_transactions.sum(:amount)
  end

  def balance_in_dollars
    balance / 100
  end

  def other_accounts
    accountable.accounts - [self]
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_accountable
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json

  # GET /accounts/1
  # GET /accounts/1.json
  def index
    @accounts = @accountable.accounts
  end

  def show
  end

  # GET /accounts/new
   def new
    @account = @accountable.accounts.new
  end

  # GET /accounts/1/edit
  def edit

  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = @accountable.accounts.new account_params
    @account.type = 'BranchAccount' unless @current_user.accounts.count.zero?
    @account.accountable_id = @current_user.id
    @account.accountable_type = @type

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @accounts = @accountable.accounts
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = @accountable.accounts.find(params[:id])
    end

    def set_accountable
      if (legal_person_signed_in?)
        # @accountable = LegalPerson.find(params[:legal_person_id])
        @accountable = current_legal_person
        @type = "LegalPerson"
      elsif (person_signed_in?)
        # @accountable = Person.find(params[:person_id])
        @accountable = current_person
        @type = "Person"
      end
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:name, :balance, :status, :parent_id, :accountable_id, :accountable_type)
    end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: [@current_user, account], local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :balance %>
    <%= form.text_field :balance, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.select :status, options_for_select([["Select one please", ""], "active", "locked", "canceled"]), class: "form-control"  %>
  </div>


  <div class="form-group">
    <%= form.label :parent_id %>
    <%= form.select :parent_id, options_for_select(@accountable.accounts.collect{ |u| [u.name, u.id] }) %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/accounts/_form2.html.erb
<%= form_for(account, as: :account, url: account.persisted? ? account_path(account) : accounts_path) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :balance %>
    <%= form.text_field :balance, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.select :status, options_for_select([["Select one please", ""], "active", "locked", "canceled"]), class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :parent_id %>
    <%= form.select :parent_id, options_for_select(["Select one please", ""] + @accountable.accounts.collect{ |u| [u.name, u.id, selected: u == account.parent] }) %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h2>Editing Account</h2>

<%= render 'form2', account: @account %>

<%= link_to 'Show', account_path(@account) %> |

<% if person_signed_in? %>
  <%= link_to 'Back', person_accounts_path(@current_user) %>
<% else %>
  <%= link_to 'Back', legal_person_accounts_path(@current_user) %>
<% end %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table class= "table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Balance</th>
      <th>Status</th>
      <th>Parent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @accountable.accounts.each do |account| %>
      <tr>
        <td><%= account.name %></td>
        <td><%= number_to_currency account.balance_in_dollars %></td>
        <td><%= account.status %></td>
        <td><%= account.parent_name %></td>
        <td>
          <div class="dropdown">
            <a class="btn btn-secondary dropdown-toggle" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Action
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <% if person_signed_in? %>
              <li><%= link_to 'View', account_path(account) %></li>
              <li><%= link_to 'Edit', edit_account_path(account) %></li>
              <li><%= link_to 'Destroy', account_path(account), method: :delete, data: { confirm: 'Are you sure?' } %></li>
              <li><%= link_to 'Transactions', account_transactions_path(account) %></li>
            <% else %>
              <li><%= link_to 'View', legal_person_account_path(account) %></li>
              <li><%= link_to 'Edit', edit_legal_person_account_path(account) %></li>
              <li><%= link_to 'Destroy', legal_person_account_path(account), method: :delete, data: { confirm: 'Are you sure?' } %></li>
              <li><%= link_to 'Transactions', account_transactions_path(account) %></li>
            <% end %>
        </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if person_signed_in? %>
  <%= link_to 'New Account', new_person_account_path, class: "btn btn-link" %>
<% else %>
  <%= link_to 'New Account', new_legal_person_account_path, class: "btn btn-link" %>
<% end %>

<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>

app/views/accounts/new.html.erb
<h2>Create a new account:</h2>

<%= render 'form', account: @account %>

<% if person_signed_in? %>
  <%= link_to 'Back', person_accounts_path %>
<% else %>
  <%= link_to 'Back', legal_person_accounts_path %>
<% end %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @account.balance %>
</p>

<p>
  <strong>Status:</strong>
  <%= @account.status %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @account.parent_id %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<% if person_signed_in? %>
  <%= link_to 'Back', person_accounts_path(@current_user) %>
<% else %>
  <%= link_to 'Back', legal_person_accounts_path(@current_user) %>
<% end %>

 